apiVersion: v1
kind: Template
metadata:
  name: new-hire-service
  annotations:
    openshift.io/display-name: new-hire service Template
    openshift.io/provider-display-name: Red Hat, Inc.
    tags: new-hire
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: new-hire-service
  spec:
    ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      app: new-hire-service
      deploymentconfig: new-hire-service
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    name: new-hire-service
  spec:
    host: new-hire-service.example.com
    port:
      targetPort: 8090
    to:
      kind: Service
      name: new-hire-service

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    name: new-hire-service
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: kie-server-new-hire:1.0
      generation: 1
      importPolicy:
        insecure: true
      name: latest
      referencePolicy:
        type: Source

-  apiVersion: apps.openshift.io/v1
   kind: DeploymentConfig
   metadata:
     annotations:
     labels:
       app: new-hire-service
     name: new-hire-service
   spec:
     replicas: 1
     revisionHistoryLimit: 10
     selector:
       app: new-hire-service
       deploymentconfig: new-hire-service
     strategy:
       activeDeadlineSeconds: 21600
       resources: {}
       rollingParams:
         intervalSeconds: 1
         maxSurge: 25%
         maxUnavailable: 25%
         timeoutSeconds: 600
         updatePeriodSeconds: 1
       type: Rolling
     template:
       metadata:
         annotations:
         creationTimestamp: null
         labels:
           app: new-hire-service
           deploymentconfig: new-hire-service
       spec:
         containers:
         - env:
           - name: JAVA_OPTIONS
             value: "-Dspring.profiles.active=openshift -Dorg.kie.server.startup.strategy=LocalContainersStartupStrategy -Dorg.kie.server.controller=ws://jbpm-console-new-hire:8080/websocket/controller -Dorg.kie.server.controller.user=user -Dorg.kie.server.controller.password=user -Dorg.kie.server.id=new-hire-service -Dorg.kie.server.location=http://new-hire-service:8090/rest/server -Dkie.maven.offline.force=true -Dkie.maven.settings.custom=/tmp/maven/repository/settings.xml -Dorg.guvnor.m2repo.dir=/tmp/maven/repository"
           image: kie-server-new-hire:latest
           name: new-hire-service
           volumeMounts:
           - mountPath: /deployments/new-hire-service.xml
             name: kie-server-state-volume
             subPath: new-hire-service.xml
         volumes:
         - configMap:
             defaultMode: 420
             items:
             - key: new-hire-service.xml
               path: new-hire-service.xml
             name: new-hire-service-kie-server-state
           name: kie-server-state-volume
     test: false
     triggers:
     - type: ConfigChange
     - imageChangeParams:
         automatic: true
         containerNames:
         - new-hire-service
         from:
           kind: ImageStreamTag
           name: 'kie-server-new-hire:1.0'
       type: ImageChange